# Generated by Django 4.1.7 on 2023-04-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keems_store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=22)),
                ('gender', models.CharField(max_length=6)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=22)),
                ('signup_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
