
'''
# refactory_mentorship_projects

## 1. Guessing game

- The guessing game that we are going to implement in python has simple rules.
- First, the program generates a random number between 1 and 99.
- Then, it asks the user to guess the number.
- If the user enters a number less than the number generated by the system,
the system tells the user that the guess is low. It then asks the user to
guess the number again.
- If the number entered by the user is greater than the system-generated
number, the system tells the user that guessed number is larger.
It then asks the user to guess the number again.
- If the user guesses the number correctly, the system informs to the user
and the game ends
'''

import random

play_again = 'yes'

while play_again.lower() == 'yes':
    number = random.randint(1, 99)
    guess_count = 0
    while guess_count < 6:
        myGuess = int(input('Guess the number I have. Psss, its between 1 and 99: '))
        guess_count += 1
        if myGuess < number:
            print('Your guess is low')
        elif myGuess > number:
            print('Your guess is larger than the number')
        else:
            print('Hooray!!! Your guess is correct! ')
            print('You made', guess_count, 'guess(es)')
            break

    if guess_count == 6:
        print('Sorry, you did not guess the number. The number was', number)

    play_again = input('Do you want to play again? (yes/no): ')

print('---------------Guessing Game has ended---------------')
